tutorial/Amostra Demo Notebook v1.ipynb
tutorial/Amostra with plans -- simple use cases.ipynb

Amostra notebook

---

README.md

added gitter to README

---

README.md

@danielballan can we add this? tutorial survey thanks!

Added a survey

---

Python-SWC.ipynb

For https://usersmeeting.ps.bnl.gov/workshops/workshop.aspx?year=2019&id=160.
Tested via https://mybinder.org/v2/gh/mrakitin/tutorial-bluesky/UM-2019-SWC-Python?urlpath=lab, works fine.

UM-2019: SWC-Python notebook

---

README.md
Welcome.md
binder/requirements.txt

To address the recent move of the repos to the new org.

NSLS-II --> bluesky in some links

---

binder/requirements.txt
scripts/beamline_configuration.py

This is an attempt to use the changes from https://github.com/bluesky/bluesky/pull/1228.
Binder from this PR branch: https://mybinder.org/v2/gh/mrakitin/tutorial-bluesky/new-bluesky-1.6.0.

Use the latest bluesky version from master (~1.6.0)

---

Export data to files with Suitcase.ipynb

For example suitcase-csv:
Based on code here https://github.com/bluesky/suitcase-csv/blob/master/suitcase/csv/__init__.py#L212

MNT: Fix file_prefix format

---

Hello Bluesky.ipynb
X-ray Absorption Fine Structure/Monochrometer Optimization.ipynb
X-ray Absorption Fine Structure/plans.py
X-ray Absorption Fine Structure/simulated_hardware.py
binder/requirements.txt
docs/source/conf.py

I will wait to merge until @bruceravel's changes go in and then rebase this on
that.

Update requirement, tweak XAFS example.

---

Hello Bluesky.ipynb

Updated to add explanations about terms and syntax
Fix
- attribute name in detector

Hello bluesky doc update

---

Let Us Do the Bookkeeping For You.ipynb
docs/Makefile
docs/source/index.rst

Documentation builds (raises-exception done correctly), otherwise just minor text changes.

Update bookkeeping for you

---

Anatomy of a Device.ipynb
docs/Makefile
docs/source/index.rst

Fixed raising exception metadata/tag issue
Added condition to docs/source/conf.py so that the exception does not cause documentation build problems

Update anatomy of a device

---

X-ray Absorption Fine Structure/plans.py

This runs to completion with all three options for how to pick the peak position ... at least for me!

Addressing #74

---

Supplemental Data.ipynb
docs/Makefile
docs/source/index.rst

Updated the Supplemental Data notebook
Note: could not add I vs time plot as when I did plt.gcf() afterwards, I only got the typical ph_det vs motor_ph

Update supplemental data

---

Powder Diffraction/Exposures and Dark Frames.ipynb
Powder Diffraction/generate_data.py
Powder Diffraction/simulated_hardware.py
Powder Diffraction/utils.py

cleaned up notebooks a bit more.  added a default smaller image mode, toggled in simulated_hardware.py

smaller image mode for binder

---

.gitignore
Hello Bluesky.ipynb
Hello Python and Jupyter.ipynb
_config.yml
_toc.yml
binder/requirements.txt
bluesky-tutorial-utils/bluesky_tutorial_utils/beamline_configuration.py
scripts/beamline_configuration.py

This is just a start at switching the tutorials from `bluesky.callbacks.mpl_plotting.LivePlot` over to the equivalents in the new bluesky-widgets library.

Use JupyterLab 3 and bluesky-widgets.

---

_toc.yml

Follow up on #102. Need to add the notebook to the table of contents.

Add Adaptive RL notebook to toc.

---

.gitignore
Array Detector (non-EPICS).ipynb
_toc.yml

Adapted from https://gist.github.com/danielballan/84484f940aea836ac997d3873c88d762

Add 'Array Detector (non-EPICS)'

---

.gitattributes
Ophyd/02 - Complex Behaviors (Set and Multiple PVs).ipynb
binder/requirements-dev.txt

Changes:
- Use new `status.wait()` method instead of manually polling.
- Use new `status.set_finished()` instead of deprecated `status._finished()`.

Update usage in set tutorial

---

INSTALLATION.md
README.md

Update instructions, and include docker option.

---

Ophyd/01 - Group Signals into Devices.ipynb
Ophyd/02 - Complex Behaviors (Set and Multiple PVs).ipynb
Ophyd/03 - Staging.ipynb
Ophyd/04 - Array Detector.ipynb

Adds a staging tutorial and also updates and tweaks to all of the others.

Add staging tutorial

---

Hello Python and Jupyter.ipynb

single commit.  should explain reasoning.  let me know if there are questions.

added a few things to hello python and Jupyter

---

.github/workflows/push_to_dockerhub.yml
binder/environment.yml

CI: bump `repo2docker-action` commit hash

---

Good Afternoon Bluesky.ipynb
Good Morning Bluesky.ipynb
Hello Python and Jupyter.ipynb
gm_user/setup.py
gm_user/user_profile.py
gm_user/user_startup.py
gm_user/user_startup_afternoon-Copy1.py
gm_user/user_startup_afternoon.py
gm_user/user_startup_night.py

Working with @jklynch on this 
@danielballan still assembling things and sorry about the messy commite with `Hello Python and Jupyter.ipynb`.  YOu said it was okay to change and so I didn't undo it when i made the mistake here.  If you want changes to  https://github.com/bluesky/tutorials/pull/136, then I will make them here first.

Um2023 bsui dosdonts
